### ISSUE TITLE
Part of debug code in USB libs uses unexistiing procedures

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jallib/jallib#153]
```
For instance, using usb_serial, and setting USB_SERIAL_DEBUG = 1, this 
activates some debug code. This code assumes the following procedures exist 
(maybe more):

  - serial_newline()
  - serial_print_spc() -- I guess "space"

Code should be migrated to match jallib repos code.

```

Original issue reported on code.google.com by `sebastie...@gmail.com` on 27 Mar 2011 at 1:17

**Comment by RobJansen62** [comment]
Can be close when new usb drivers are uploaded. All print functions are now from the 'serial_hardware' library

**Comment by RobJansen62** [comment]
Closed since no longer applicable. Updated USB drivers are using the serial hardware library.
