### ISSUE TITLE
Missing print procedure for float variables

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jallib/jallib#197]
```
Since the compiler supports floating point variables, the Print library should 
be extended to print these type of variables.

```

Original issue reported on code.google.com by `robhamerling` on 24 Jul 2014 at 9:14

**Comment by RobJansen62** [comment]
Float procedure added to print library. Solution is based on the float to ascii procedure described by Kyle in funcs.jal.
Will be part of Jallib release 1.6.0.
