### ISSUE TITLE
Bug in include/external/storage/sd_card.jal (with fix)

### ISSUE THREAD

**Issue by gw1urf** [jallib/jallib#217]
sd_print_error() has the following prototype:

**procedure sd_print_error(byte in device) is**

When called, it causes my test program to hang. Looking at the procedure prototypes in 
print.jal, I changed sd_print_error to use:

**procedure sd_print_error(volatile byte out device) is**

With this change, printing error status works.

**Comment by jallib** [comment]
I have added you as a committer, are you able to make the fix?

**Comment by gw1urf** [comment]
I'd better read some help pages first - never committed anything to GitHub before! - but yes, I'll have a go, thanks.

**Comment by gw1urf** [comment]
Fix committed.
