### ISSUE TITLE
JAL Compiler jalv2.4q6 does not support new PICs with 64 banks

### ISSUE THREAD

**Issue by RobJansen62** [jallib/jallib#222]
The current JAL Compiler jalv2.4q6 supports PICs up to 32 banks. Currently PICs are available with 64 banks. These chips cannot be supported with the current JAL Compiler. Examples of PICs are given below.

16f15313  16f15323  16f15324 16f15325 16f15344 16f15345 16f15354 16f15355 16f15356 16f15375     
16f15376  16f15385 16f15386 16f18426 16f18446 16f18857 16f18877  16f19155 16f19156  16f19175    
16f19176  16f19185 16f19186 16f19195 16f19196 16f19197

**Comment by jallib** [comment]
Solved with compiler version jalv25.

**Comment by RobJansen62** [comment]
Issue also registered in the compiler repository, see: https://github.com/jallib/jalv2compiler/issues/4
