### ISSUE TITLE
Blink a LED samples of 16F145x use an input-only pin A0

### ISSUE THREAD

**Issue by robhamerling** [jallib/jallib#228]
The 16F145x series have some input-only pins, in particular A0 and A1. Nevertheless the blink-a-led samples use pin_A0. 

The blink-a-led.py script avoids input-only pins for blink-a-led samples when a candidate pin has no corresponding TRIS bit (no 'pin_xy_direction' alias). The device files of the 16F145x do contain a pin_A0_direction, even though there is no corresponding TRIS bit. So it looks like the cause is the pic2jal script.

**Comment by RobJansen62** [comment]
Fixed. Adapted pic2jal.py. Updated blink-a-led sample files added
