### ISSUE TITLE
Download ZIP is does not represent the data in the devices folder

### ISSUE THREAD

**Issue by Anobium** [jallib/jallib#232]
The download ZIP is does not represent the data in the devices folder.  

Examples are K42s and K83s.  I wonder which others are different?

Can the ZIP be refreshed?

**Comment by RobJansen62** [comment]
Hi Anonbium,

I checked this but I do see k42 and k83 device files in the zipfile from the master. I also checked the file CHANGELOG and it seemed to be the last version. Next to that they are also present in the bee package found at: http://justanotherlanguage.org/downloads

Let me know when you found them. 

Thanks

Kind regards,
Rob

**Comment by Anobium** [comment]
Thank you for the urls.

All good now.

**Comment by Anobium** [comment]
Thank you for the urls.

All good now.
