### ISSUE TITLE
Wrong configuration memory declaration in device file of 18FxxQ43

### ISSUE THREAD

**Issue by robhamerling** [jallib/jallib#235]
In the Programming Specifications of the 18FxxQ43 configuration memory is specified as BYTES (not words!), and these PICs have 10 CONFIGx bytes. 
Strangely enough the device file specifies 18 bytes (or 9 words splitted in CONFIGxL and CONFIGxH).  
The discrepancy (the 'missing' 10th word or byte) may be caused by: CONFIG9 is reserved (and reads back as 0xFF).

**Comment by RobJansen62** [comment]
Updated pic2jal.py script and re-created (and uploaded) all device files.
