### ISSUE TITLE
PxM missing  for CCP4CON ... CCP10CON

### ISSUE THREAD

**Issue by eureur** [jallib/jallib#240]
Hi

The 18F PIC series seem to be missing their P4M ..P10M bit*2 output configuration bits for the higher CCPxCOn registers. 

For instance the PIC18F67k22 has CCP4CON to CCP10CON, all with P4M to P10M on bit 6 and 7. This is not in the device files. 
The lower CCPxCON do have them:

iMac-2:620_development eur$ grep -e "CCP.CON_P.M" ~/jallib/include/device/18f67k22.jal 
var volatile bit*2  CCP3CON_P3M               at CCP3CON : 6
var volatile bit    CCP3CON_P3M0              at CCP3CON : 6
var volatile bit    CCP3CON_P3M1              at CCP3CON : 7
var volatile bit*2  CCP2CON_P2M               at CCP2CON : 6
var volatile bit    CCP2CON_P2M0              at CCP2CON : 6
var volatile bit    CCP2CON_P2M1              at CCP2CON : 7
var volatile bit*2  CCP1CON_P1M               at CCP1CON : 6
var volatile bit    CCP1CON_P1M0              at CCP1CON : 6
var volatile bit    CCP1CON_P1M1              at CCP1CON : 7

**Comment by RobJansen62** [comment]
Since it is consistent with the datasheet I close this issue
